config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :index, :show]
  resources :goals, only: [:new, :create, :destroy, :index]
  resource :session, only: [:new, :create, :destroy]

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :user_id, :body, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :username, uniqueness: true

  has_many :goals

  after_initialize :ensure_session_token

  attr_reader :password

  validates :password, length: { minimum: 6, allow_nil: true }

  def self.find_by_credentials(username, password)
    possible_user = User.find_by(username: username)
    return nil unless possible_user
    BCrypt::Password.new(possible_user.password_digest).is_password?(password) ? possible_user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :login, :logout, :logged_in?, :check_login

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def check_login
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :check_login

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.privacy = (goal_params[:privacy].nil? ? false : true)
    @goal.user_id = current_user.id
    unless @goal.save
      flash[:errors] = @goal.errors.full_messages
    end
    redirect_to goals_url
  end

  def index
    @goals = Goal.all.where(user_id: current_user.id)
  end

  def destroy
    @goal = Goal.find_by(id: params[:id])
    @goal.delete
    redirect_to goals_url
  end

  private

  def goal_params
    params.require(:goal).permit(:title,:body,:privacy)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
      )
    if @user
      login(@user)
      redirect_to goals_url
    else
      flash[:errors] = ["user credentials invalid"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      render :new
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>All Goals</h1>

<ul>

  <% @goals.each do |goal| %>
      <li><%= goal.title%></li>
      <br>
      <%= goal.user.username %>
      <br>
      <%= goal.body%>
      <%= button_to "Delete Goal", goal_url(goal), method: :delete %>
      <br>
      <br>
    <%end%>
</ul>


<%= link_to "Add Goal", new_goal_url %>

app/views/goals/new.html.erb
<h1>Goals</h1>

<form class="" action="<%=goals_url%>" method="post">
  <%= auth_token %>

  <input type="text" name="goal[title]" id="goal_title" value="" >
  <input type="text" name="goal[body]" id="goal_body" value="" >
  <input type="text" name="goal[status]" id="goal_status" value="" >

  <label>Goals are public by default</label>

  <input type="checkbox" name="goal[privacy]" id="goal_privacy" value="Private" > Privacy <br>

  <input type="submit" value="Add Goal">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <label> Logged in: <%= current_user.username if current_user %></label>
  <%= button_to "sign out", session_url, method: :delete %>
<%else%>
  <%= button_to "signin", new_session_url, method: :get %>
  <%= button_to "signup", new_user_url, method: :get %>
<%end%>

<%= render "shared/errors" %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <%= error%>
  <%end%>
<%end%>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <%@users.each do |user|%>
  <%= link_to user.username, user_url(user)%>
  <%end%>
</ul>

app/views/users/new.html.erb
<h1>sign up</h1>

<form class="" action="<%=users_url%>" method="post">
  <%= auth_token %>

  <input type="text" name="user[username]" id="username"value="" >

  <input type="password" name="user[password]" id="password" value="">

  <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<%= @user.username %>

<ul>
<% @user.goals.where(privacy: false).each do |goal| %>
  <li>Start Date: <%= goal.created_at %></li>
  <li><%= goal.title %></li>
  <li><%= goal.body %></li>
  <li><%= goal.status %></li>
  <br>
<%end%>
</ul>